# Generated by Django 5.1.3 on 2024-12-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
